id: P007047
initial_creation_type: ocr
source_metadata:
  id: bdr:W30540
  title: དྲིས་ལན་ལུང་དང་རིགས་པའི་འབྲུག་སྒྲ་སོགས
  author: ''
  volumes:
    f50eb616d8b84293bc131be2576f965e:
      image_group_id: I6458
      title: ''
      volume_number: 1
      total_pages: 276
      base_file: v001.txt
ebook_metadata:
  title: དྲིས་ལན་ལུང་དང་རིགས་པའི་འབྲུག་སྒྲ་སོགས
  author: ''
  sku: P007047
  cover: cover.jpg
  layers:
  - pagination
